### ISSUE TITLE
Week 2 deliverables

### ISSUE THREAD

**Issue by hashmeet02** [yemregumus/IntelliCycles#2]
- [x] edits to the Network Diagram- @yemregumus 
       Frontend and backend deliverables should be in parallel because the occur simultaneously.
       Every block should have the responsible person associated with it. 
- [x] Github deliverables to be set up - @hashmeet02 
- [x] Risk Matrix- @okuti2 
- [x] Setup/Initializing the repository/project- @busycaesar 
        @hashmeet02 , @okuti2 work on frontend
        @yemregumus , @busycaesar work on backend

**Comment by yemregumus** [comment]
Edits to the Network Diagram completed.

**Comment by okuti2** [comment]
done and uploaded
