### ISSUE TITLE
Iteration #3

### ISSUE THREAD

**Issue by hashmeet02** [yemregumus/IntelliCycles#28]
- [ ] calendar view- @okuti2 
- [x] added queries for crud apis for reminders, habits and events @busycaesar 
- [x] updated backend logic to handle streak calculations and reset streak to 0 if a day/week is missed @yemregumus 
- [ ] integrate crud apis with the the frontend pages- @hashmeet02 
- [ ] chatbot api integration- backend

**Comment by yemregumus** [comment]
Add streak calculation for habit completion
- Added completed_at column to userActivity table to store habit completion timestamps.
- Created updateHabitCompletion function to update habit completion status and calculate streak count.
- Implemented calculateStreak function to determine the number of consecutive days/weeks a habit has been completed.
- Updated backend logic to handle streak calculations and reset streak to 0 if a day/week is missed.
- Exported updateHabitCompletion and calculateStreak function for frontend integration.
